## MI Rectangle

In [2]:
# load library
library(readxl)
library(MLEcens)

In [3]:
data_df = read.csv("data.csv")

In [4]:
# clean the dataframe
data_df = data.frame(lapply(data_df, as.numeric))
data_df = data_df[data_df$R != data_df$Z, ]
rownames(data_df) = NULL
head(data_df)

  L R  W  Z
1 1  7 23 1000
2 1 13 23 1000
3 1 15 23 1000
4 1 15 23 1000
5 3 14 23 1000
6 7 10 23 1000

In [5]:
# define the boundaries
num_samples = dim(data_df)[1]
X1 = rep(0, num_samples)
X2 = rep(1, num_samples)
Y1 = rep(0, num_samples)
Y2 = rep(1, num_samples)
boundary_frame = data.frame(X1, X2, Y1, Y2)
boundary_frame[which(data_df$W == data_df$Z), ][, c("Y1", "Y2")] = 1
boundary_frame

   X1 X2 Y1 Y2
1  0  1  0  1
2  0  1  0  1
3  0  1  0  1
4  0  1  0  1
5  0  1  0  1
6  0  1  0  1
7  0  1  0  1
8  0  1  0  1
9  0  1  0  1
10 0  1  0  1
11 0  1  0  1
12 0  1  0  1
13 0  1  0  1
14 0  1  0  1
15 0  1  0  1
16 0  1  0  1
17 0  1  0  1
18 0  1  0  1
19 0  1  0  1
20 0  1  0  1
21 0  1  0  1
22 0  1  0  1
23 0  1  0  1
24 0  1  0  1
25 0  1  0  1
26 0  1  0  1
27 0  1  1  1
28 0  1  0  1
29 0  1  0  1
30 0  1  0  1
⋮  ⋮  ⋮  ⋮  ⋮
67 0  1  0  1
68 0  1  0  1
69 0  1  0  1
70 0  1  0  1
71 0  1  0  1
72 0  1  0  1
73 0  1  0  1
74 0  1  0  1
75 0  1  0  1
76 0  1  0  1
77 0  1  0  1
78 0  1  0  1
79 0  1  0  1
80 0  1  0  1
81 0  1  0  1
82 0  1  0  1
83 0  1  0  1
84 0  1  0  1
85 0  1  0  1
86 0  1  0  1
87 0  1  0  1
88 0  1  0  1
89 0  1  1  1
90 0  1  0  1
91 0  1  1  1
92 0  1  0  1
93 0  1  0  1
94 0  1  0  1
95 0  1  1  1
96 0  1  0  1

In [6]:
# rect
rect = computeMLE(R=data.matrix(data_df), B=data.matrix(boundary_frame))$rects
prob = computeMLE(R=data.matrix(data_df), B=data.matrix(boundary_frame))$p

In [7]:
# dataframe
df = data.frame(rect, prob)
colnames(df) = c("l", "r", "w", "z", "p")
write.csv(df, "MI.csv")

In [8]:
df["p"] = round(df["p"], 4)
df

   l  r  w  z    p
1   5  7 23 1000 0.0437
2   5  7 13   13 0.0208
3   3  7 17   17 0.0104
4   1  7 16   16 0.0104
5   5  7 11   12 0.0208
6   7  9 19   19 0.0104
7   8  9 23 1000 0.0235
8   9 10 23 1000 0.0639
9   9 10 15   15 0.0156
10 10 11 23 1000 0.1649
11 10 11 15   16 0.0312
12  9 11 17   18 0.0312
13 10 11 14   15 0.0156
14 10 12 16   17 0.0104
15 11 12 23 1000 0.0379
16  9 12 22   22 0.0104
17 10 12 23   23 0.0104
18 12 13 23 1000 0.1682
19 12 13 20   20 0.0104
20 13 14 17   18 0.0312
21 13 14 20   21 0.0208
22 13 14 19   20 0.0104
23 14 15 23 1000 0.1548
24 14 15 23   23 0.0104
25 15 16 23 1000 0.0619